    CREATE TABLE TB_CLIENTS(
        ID BIG SERIAL AUTO INCREMENT PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL,
        PHONE VARCHAR(255) NOT NULL,
        CPF VARCHAR(255) NOT NULL UNIQUE,
        EMAIL VARCHAR(255) NOT NULL UNIQUE,
        ADDRESS TEXT NOT NULL
    );

    CREATE TABLE TB_CONSULTANTS(
        ID BIG SERIAL AUTO INCREMENT PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL,
        PHONE VARCHAR(255) NOT NULL,
        CPF VARCHAR(255) NOT NULL UNIQUE,
        EMAIL VARCHAR(255) NOT NULL UNIQUE,
        ADDRESS TEXT NOT NULL
    );

    CREATE TABLE TB_MANAGERS(
        ID BIG SERIAL AUTO INCREMENT PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL,
        PHONE VARCHAR(255) NOT NULL,
        CPF VARCHAR(255) NOT NULL UNIQUE,
        EMAIL VARCHAR(255) NOT NULL UNIQUE,
        ADDRESS TEXT NOT NULL
    );

    CREATE TABLE TB_VEHICLES(
        ID BIG SERIAL AUTO INCREMENT PRIMARY KEY,

        MODEL VARCHAR(255) NOT NULL,
        BRAND VARCHAR(255) NOT NULL
    );


    CREATE TABLE TB_ORDERS(
        ID BIG SERIAL AUTO INCREMENT PRIMARY KEY,

        STARTTIME TIMESTAMPTZ WITH TIME ZONE NOT NULL,
        FINALTIME DATE,
        DISCOUNT DOUBLE PRECISION,
        FINALAMOUNT DOUBLE PRECISION,

        FOREIGN KEY(ID_CLIENT) REFERENCES TB_CLIENTS(ID),
        FOREIGN KEY(ID_CONSULTANT) REFERENCES TB_CONSULTANTS(ID),
        FOREIGN KEY(ID_MANAGER) REFERENCES TB_MANAGERS(ID),
        FOREIGN KEY(ID_VEHICLE) REFERENCES TB_VEHICLES(ID)
    );
